<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 5.0 (Python 3.7.0 on win32)" generated="20220430 23:47:11.591" rpa="false" schemaversion="3">
<suite id="s1" name="demoProjects" source="D:\demoProjects">
<suite id="s1-s1" name="Testcases" source="D:\demoProjects\testcases">
<suite id="s1-s1-s1" name="GUI scripts" source="D:\demoProjects\testcases\GUI_scripts.robot">
<test id="s1-s1-s1-t1" name="test" line="135">
<kw name="Log" library="BuiltIn">
<arg>@{nums}[0]</arg>
<doc>Logs the given message with the given level.</doc>
<msg timestamp="20220430 23:47:12.476" level="FAIL">Value of variable '@{nums}[0]' is not list or list-like.</msg>
<status status="FAIL" starttime="20220430 23:47:12.476" endtime="20220430 23:47:12.476"/>
</kw>
<kw name="Log" library="BuiltIn">
<arg>@{nums}</arg>
<doc>Logs the given message with the given level.</doc>
<status status="NOT RUN" starttime="20220430 23:47:12.476" endtime="20220430 23:47:12.476"/>
</kw>
<status status="FAIL" starttime="20220430 23:47:12.476" endtime="20220430 23:47:12.476">Value of variable '@{nums}[0]' is not list or list-like.</status>
</test>
<status status="FAIL" starttime="20220430 23:47:12.414" endtime="20220430 23:47:12.476"/>
</suite>
<status status="FAIL" starttime="20220430 23:47:11.707" endtime="20220430 23:47:12.492"/>
</suite>
<status status="FAIL" starttime="20220430 23:47:11.660" endtime="20220430 23:47:12.493"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="demoProjects">demoProjects</stat>
<stat pass="0" fail="1" skip="0" id="s1-s1" name="Testcases">demoProjects.Testcases</stat>
<stat pass="0" fail="1" skip="0" id="s1-s1-s1" name="GUI scripts">demoProjects.Testcases.GUI scripts</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20220430 23:47:12.460" level="ERROR">[ DataDriver ] Error in robot file:
  File "D:\demoProjects\testcases\GUI_scripts.robot", line 0</msg>
<msg timestamp="20220430 23:47:12.460" level="ERROR">In source file:
  File "D:/demoProjects/testData/test_user_data.xlsx", line 0</msg>
<msg timestamp="20220430 23:47:12.476" level="ERROR">Calling method '_start_suite' of listener 'DataDriver' failed: FileNotFoundError: File attribute was not a full path. Tried to find D:/demoProjects/testData/test_user_data.xlsx but file does not exist.</msg>
</errors>
</robot>
